#!/bin/bash

chromiumStatus='false'
firefoxStatus='false'

# Set vars
case ${1^} in #ensure first letter is uppercase
"School" | "Chrome" )
	chromiumStatus='true'
	firefoxStatus='false'
	;;
"Home" | "Firefox")
	chromiumStatus='false'
	firefoxStatus='true'
	;;
"Both" |"Dual" )
	chromiumStatus='true'
	firefoxStatus='true'
	;;
"Neither" |"Off" )
	chromiumStatus='false'
	firefoxStatus='false'
	;;
esac

if $chromiumStatus; then
	pkill chromium --signal CONT
else
	pkill chromium --signal STOP
fi

if $firefoxStatus; then
	pkill firefox-esr --signal CONT
else
	pkill firefox-esr --signal STOP
fi
