#!/bin/bash

chromiumStatus='false'
firefoxStatus='false'

# Set vars
case ${1^} in #ensure first letter is uppercase
"School" | "Chrome" )
	chromiumStatus='true'
	firefoxStatus='false'
	;;
"Home" | "Firefox")
	chromiumStatus='false'
	firefoxStatus='true'
	;;
"Both" |"Dual" )
	chromiumStatus='true'
	firefoxStatus='true'
	;;
"Neither" |"Off" )
	chromiumStatus='false'
	firefoxStatus='false'
	;;
esac

chromename='/usr/lib/chromium/*'
firefoxname='/usr/lib/firefox-esr/*'

if $chromiumStatus; then
	pkill -f "$chromename" --signal CONT
else
	pkill -f "$chromename" --signal STOP
fi

if $firefoxStatus; then
	pkill -f "$firefoxname" --signal CONT
else
	pkill -f "$firefoxname" --signal STOP
fi
