#!/bin/bash

InstallList=~/toInstall.txt
if [ -e $InstallList ]
then
	cat $InstallList

	if [ "$1" == "Download" ]
	then
		sudo apt -dy install `cat $InstallList`
	elif [ "$1" == "Install" ]
	then
		nice -n 20 sudo apt install `cat $InstallList`
	elif [ "$1" == "Clean" ]
	then
		rm $InstallList
	fi
fi
if [ "$1" == "Edit" ]
then
	nano $InstallList
elif [ "$1" != "${1^}" ] #first letter of first command is lowercase
then
        echo "================"
	for pkg in "$@"
	do
		echo $pkg
		echo $pkg >> $InstallList
	done
fi

