#!/bin/bash

InstallList=~/toInstall.txt

cat $InstallList

if [ "$1" == "Download" ]
then
	sudo apt -dy install `cat $InstallList`
elif [ "$1" == "Install" ]
then
	nice -n 20 sudo apt install `cat $InstallList`
elif [ "$1" == "Clean" ]
then
        > $InstallList
elif [ "$1" == "Edit" ]
then
	nano $InstallList
else
        echo "================"
	for pkg in "$@"
	do
		echo $pkg
		echo $pkg >> $InstallList
	done
fi
