#!/bin/bash
set -e

# Make sure we have root
[[ $UID = 0 ]] || { echo "Please have root powers when executing this script"; exit; }

# Grab all internet-dependent things first
nice -n 19 apt update

# Don't bother with DebDelta: the package cache will always be empty
# TODO: Use apt-cacher-ng 's precaching feature
nice -n 19 apt dist-upgrade -dy
echo "$@"
echo "${@%$'\n'}" | od -vtc -to1
nice -n 19 apt install -dy "${@%$'\n'}"

# Install downloaded updates
nice -n 19 apt upgrade
nice -n 19 installLater Install

# Cleanup
apt clean # I use apt-cacher-ng, so no need for duplicates
installLater Clean # Flushes installLater list
