#!/bin/bash

#Standardize directory
cd ~

# Bump fun log, for, well, fun
log-fun-data

# Make a temporary file for MR's log
DATE=$(date +%b%d-%T)
TEMPFILE=$(mktemp -t mr-status-$DATE.XXXXX)

# Start mr fetch in background
mr fetch --progress &>> $TEMPFILE

# Construct scriptname of root file
MAGICROOT="$0""-root"
echo $MAGICROOT
echo $TEMPFILE

# Get list of InstallLater packages
TOINSTALL=`installLater List`

echo "Starting Apt upgrades..."
sudo bash $MAGICROOT $TOINSTALL
if [ "$?" -eq "0" ]; then
	printf "\nApt upgrade successful, cleaning installLater\n"
	installLater Clean;
fi

printf "\n Apt upgrades complete, waiting for MR fetch \n"

# Catch up on any not-yet-done MR commands
mr online &>> $TEMPFILE &

wait
printf "MR Results: \n"
cat $TEMPFILE

# Bump log again, for more fun
log-fun-data
