#!/bin/bash
set -e

# Make sure we have root
[[ $UID = 0 ]] || { echo "Please have root powers when executing this script"; exit; }

# Grab all internet-dependent things first
nice -n 19 apt update
nice -n 20 debdelta-upgrade -v
# Debdelta won't download new packages needed for update
nice -n 19 apt dist-upgrade -dy
nice -n 19 installLater Download

# Install downloaded updates
nice -n 19 apt upgrade
nice -n 19 installLater Install

# Cleanup
apt clean # I use apt-cacher-ng, so no need for duplicates
installLater Clean # Flushes installLater list
