#!/bin/bash

chromiumStatus='false'
firefoxStatus='false'
torrentManagerStatus='false'

echo ${1^}

# Set vars
case ${1^} in #ensure first letter is uppercase
"SchoolStrict" )
	chromiumStatus='true'
	firefoxStatus='false'
	torrentManagerStatus='false'
	;;
"SchoolLazy" )
	chromiumStatus='true'
	firefoxStatus='true'
	torrentManagerStatus='false'
	;;
"HomeStrict")
	chromiumStatus='false'
	firefoxStatus='true'
	torrentManagerStatus='true'
	;;
"HomeLazy" )
	chromiumStatus='true'
	firefoxStatus='true'
	torrentManagerStatus='true'
	;;
"Off" )
	chromiumStatus='false'
	firefoxStatus='false'
	torrentManagerStatus='false'
	;;
esac

chromename='/usr/lib/chromium/*'
firefoxname='/usr/lib/firefox-esr/*'
torrentManagerName='qbittorrent'

if $chromiumStatus; then
	pkill -f "$chromename" --signal CONT
else
	pkill -f "$chromename" --signal STOP
fi

if $firefoxStatus; then
	pkill -f "$firefoxname" --signal CONT
else
	pkill -f "$firefoxname" --signal STOP
fi

if $torrentManagerStatus; then
	pkill -f "$torrentManagerName" --signal CONT
else
	pkill -f "$torrentManagerName" --signal STOP
fi
	
